- src: https://github.com/redhat-sap/sap_rhsm.git
- src: https://github.com/redhat-sap/sap-hostagent.git
- src: https://github.com/redhat-sap/sap_hana_deployment.git
- src: https://github.com/redhat-sap/sap_s4hana_deployment.git
- src: https://github.com/linux-system-roles/sap-preconfigure.git
- src: https://github.com/linux-system-roles/sap-hana-preconfigure.git
- src: https://github.com/linux-system-roles/sap-netweaver-preconfigure.git
- src: https://github.com/linux-system-roles/storage.git
